name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1   
    - name: Setup nuget
      uses: NuGet/setup-nuget@v1 
    - name: Restore dependencies
      run: nuget restore
    - name: Build Release
      run: msbuild iDeviceToolbox.sln -property:Configuration=Release -t:rebuild
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
       path: .\bin\Release
